version: "3.9"

services:
    # database service
    service_db:
        platform: linux/x86_64
        image: postgres
        container_name: ct_postgres
        restart: unless-stopped
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_DB: $DB_NAME
            POSTGRES_PASSWORD: $DB_PASSWORD
        volumes:
            - vol_postgres:/var/lib/postgresql/data
        networks:
            - db_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    # main app service
    service_app:
        restart: unless-stopped
        depends_on:
            service_db:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ct_app
        ports:
            - "3001:3001"
        env_file: app.env
        networks:
            - db_network

    # testing service
    service_test:
        profiles: ["cli-only"]
        depends_on:
            service_db:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ct_test
        env_file: app.env
        networks:
            - db_network

networks:
    db_network:
        driver: bridge

volumes:
    vol_postgres:
        driver: local
