// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: deposits.sql

package db

import (
	"context"
)

const createDeposit = `-- name: CreateDeposit :one
INSERT INTO "deposits" (
    "account_id", "amount"
) VALUES (
    $1, $2
)
RETURNING id, amount, account_id, created_at
`

type CreateDepositParams struct {
	AccountID int64   `json:"account_id"`
	Amount    float64 `json:"amount"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, createDeposit, arg.AccountID, arg.Amount)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.AccountID,
		&i.CreatedAt,
	)
	return i, err
}
