// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateDeposit(ctx context.Context, arg CreateDepositParams) (Deposit, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateWithdraw(ctx context.Context, arg CreateWithdrawParams) (Withdraw, error)
	GetAccount(ctx context.Context, id int64) (Account, error)
	GetAccounts(ctx context.Context) ([]Account, error)
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (Account, error)
}

var _ Querier = (*Queries)(nil)
